name: Build Windows

on: [push, pull_request]
env:
  VULKAN_SDK_VERSION: '1.2.131.1'
jobs:
  build_windows:
    strategy:
      matrix:
        # build-type: ['play!', 'psfplayer']
        target-platform: ['x86', 'x64']
    runs-on: windows-latest
    steps:
    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: ${{ runner.os }}-QtCache
    - name: Install Vulkan SDK
      run: |
        cd $RUNNER_WORKSPACE
        echo "::warning::https://sdk.lunarg.com/sdk/download/${{ env.VULKAN_SDK_VERSION }}/windows/VulkanSDK-${{ env.VULKAN_SDK_VERSION }}-Installer.exe?Human=true"
        curl --output  VulkanSDK.exe https://sdk.lunarg.com/sdk/download/${{ env.VULKAN_SDK_VERSION }}/windows/VulkanSDK-${{ env.VULKAN_SDK_VERSION }}-Installer.exe?Human=true
        .\VulkanSDK.exe /S
        echo "VULKAN_SDK=C:\VulkanSDK\${{ env.VULKAN_SDK_VERSION }}" >> $GITHUB_ENV
        echo "::warning::${VULKAN_SDK}"

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        cached: ${{ steps.cache-qt.outputs.cache-hit }}