name: Build Linux Arm64

on: [push, pull_request]
jobs:
  build_linux_arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker Buildx Build
        run: |
            docker buildx build \
            --file build_docker/dockerfile.arm64 .
