name: Build PsfPlayer Windows

on: [push, pull_request]
env:
  QT_VERSION: '5.15.2'
jobs:
  build_windows:
    strategy:
      matrix:
        build-type: ['Visual Studio 16 2019']
        target-platform: ['x64']
        config-type: ['Release']
        qt-arch: ['win64_msvc2019_64']
        installer-script: ['installer64.nsi']
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Run Tests
      run: |
        git fetch --tags
        git describe
