name: Build Android

on: [push, pull_request]
env:
  ANDROID_NDK_VERSION: '21.3.6528147'
  ANDROID_CMAKE_VERSION: '3.10.2.4988404'
jobs:
  build_android:
    strategy:
      matrix:
        build-type: ['lib']
        arch-type: ['armeabi-v7a', 'x86', 'x86_64', 'arm64-v8a']
    runs-on: ubuntu-latest
    steps:
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    - name: Cache NDK
      id: ndk-cache
      uses: actions/cache@v2
      with:
        path: /usr/local/lib/android/sdk/ndk
        key: ${{ runner.os }}-NdkCache-${{ env.ANDROID_NDK_VERSION }}
    - name: Install Android SDK dependencies
      run: |
        echo y | sdkmanager "ndk;${{ env.ANDROID_NDK_VERSION }}"
        echo y | sdkmanager "cmake;${{ env.ANDROID_CMAKE_VERSION }}"
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Force Fetch Git Tags
      run: git fetch --tags --force
    - name: Set SHORT_HASH
      run: echo "::set-output name=VALUE::${LONG_HASH:0:8}"
      id: short_hash
      env:
        LONG_HASH: ${{ github.sha }}
    - name: Build Library
      if: ${{ matrix.build-type == 'lib' }}
      run: |
        cd build_android
        ./gradlew
        ./gradlew externalNativeBuildRelease -P${{ matrix.arch-type }}
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: library
        path: build_android/build/intermediates/cmake/release/obj/
